package:
    name: django-celery
    version: "3.2.0.a1"

source:
    git_rev: "3.2.0.a1"
    git_url: https://github.com/axiom-data-science/django-celery

requirements:
    build:
        - python
        - setuptools
    run:
        - celery

test:
    imports:
        - djcelery

about:
    home: https://github.com/celery/django-celery
    license: New BSD License
    summary: 'An ocean data toolkit developed and used by Axiom Data Science'
