package:
    name: django-celery
    version: "3.1.17"

source:
  fn: django-celery-3.1.17.tar.gz
  url: https://pypi.python.org/packages/source/d/django-celery/django-celery-3.1.17.tar.gz
  md5: a3abc9674b0680469b0694a254dd7019

requirements:
    build:
        - python
        - setuptools
    run:
        - celery

test:
    imports:
        - djcelery

about:
    home: https://github.com/celery/django-celery
    license: New BSD License
    summary: 'Celery Integration for Django'
