package:
  name: docker-py
  version: "1.7.2"

source:
  fn: docker-py-1.7.2.tar.gz
  url: https://pypi.python.org/packages/source/d/docker-py/docker-py-1.7.2.tar.gz
  md5: b1007b53eabb0e385d52b9a4fd3095b1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docker-py = docker-py:main
    #
    # Would create an entry point called docker-py that calls docker-py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.5.2
    - six >=1.4.0
    - websocket-client >=0.32.0

  run:
    - python
    - requests >=2.5.2
    - six >=1.4.0
    - websocket-client >=0.32.0

test:
  # Python imports
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.ssladapter
    - docker.unixconn
    - docker.utils
    - docker.utils.ports

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage ==3.7.1
    - flake8 ==2.4.1
    - mock ==1.0.1
    - pytest ==2.7.2
    - pytest-cov ==2.1.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/docker/docker-py/
  license: Apache Software License
  summary: 'Python client for Docker.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
