package:
  name: django-nested-inline
  version: "0.3.5"

source:
  fn: django-nested-inline-0.3.5.tar.gz
  url: https://pypi.python.org/packages/source/d/django-nested-inline/django-nested-inline-0.3.5.tar.gz
  md5: e59b87c90a0eebcccf902ae243121578
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django-nested-inline = django-nested-inline:main
    #
    # Would create an entry point called django-nested-inline that calls django-nested-inline.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - example
    - nested_inline

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/s-block/django-nested-inline
  license: MIT License
  summary: 'Recursive nesting of inline forms for Django Admin'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
