package:
  name: pyinotify
  version: !!str 0.9.6

source:
  fn: pyinotify-0.9.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pyinotify/pyinotify-0.9.6.tar.gz
  md5: 8e580fa1ff3971f94a6f81672b76c406

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pyinotify

about:
  home: http://github.com/seb-m/pyinotify
  license: MIT License
