package:
  name: flower
  version: "0.8.3"

source:
  fn: flower-0.8.3.tar.gz
  url: https://pypi.python.org/packages/source/f/flower/flower-0.8.3.tar.gz
  md5: 09d4dec422ed6c4a10584b5fce6008d6

build:
  number: 0
  entry_points:
    - flower = flower.__main__:main

requirements:
  build:
    - python
    - setuptools
    - celery >=2.5.0
    - tornado >=4.0.0
    - babel
    - pytz
    - futures

  run:
    - python
    - setuptools
    - celery >=2.5.0
    - tornado >=4.0.0
    - babel
    - pytz
    - futures

test:
  # Python imports
  imports:
    - flower
    - flower.api
    - flower.utils
    - flower.utils.backports
    - flower.views

  commands:
    - flower --help

about:
  home: https://github.com/mher/flower
  license: BSD License
  summary: 'Celery Flower'
