package:
  name: pecan
  version: "1.0.4"

source:
  fn: pecan-1.0.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pecan/pecan-1.0.4.tar.gz
  md5: 02d26c5be8faa64c35b57ed9205742a6
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pecan = pecan:main
    #
    # Would create an entry point called pecan that calls pecan.main()

    - pecan=pecan.commands:CommandRunner.handle_command_line
    - gunicorn_pecan=pecan.commands.serve:gunicorn_run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - webob >=1.2dev
    - mako >=0.4.0
    - webtest >=1.3.1
    - six
    - logutils >=0.3

  run:
    - python
    - setuptools
    - webob >=1.2dev
    - mako >=0.4.0
    - webtest >=1.3.1
    - six
    - logutils >=0.3

test:
  # Python imports
  imports:
    - pecan
    - pecan.commands
    - pecan.compat
    - pecan.ext
    - pecan.middleware
    - pecan.scaffolds
    - pecan.tests
    - pecan.tests.middleware
    - pecan.tests.scaffold_fixtures
    - pecan.tests.templates

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pecan --help
    - gunicorn_pecan --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - genshi >=0.7
    - gunicorn
    - jinja2
    - logutils >=0.3
    - mako >=0.4.0
    - mock
    - six
    - sqlalchemy
    - virtualenv
    - webob >=1.2dev
    - webtest >=1.3.1
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/pecan/pecan
  license: BSD License
  summary: 'A WSGI object-dispatching web framework, designed to be lean and fast, with few dependencies.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
